DROP DATABASE IF EXISTS LIBRARY;

CREATE DATABASE LIBRARY;

USE LIBRARY;

DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK(
Book_id INT AUTO_INCREMENT,
Isbn BIGINT,
Title VARCHAR(210),
PRIMARY KEY(Book_id));

DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(
Author_id INT AUTO_INCREMENT,
Name VARCHAR(100),
PRIMARY KEY(Author_id));

DROP TABLE IF EXISTS BOOK_AUTHORS;
CREATE TABLE BOOK_AUTHORS(
Author_id INT,
Book_id INT,
PRIMARY KEY(Author_id,Book_id),
FOREIGN KEY(Author_id) REFERENCES AUTHORS(Author_id),
FOREIGN KEY(Book_id) REFERENCES BOOK(Book_id));

DROP TABLE IF EXISTS BORROWER;
CREATE TABLE BORROWER(
Card_id INT AUTO_INCREMENT,
Ssn CHAR(11) NOT NULL,
Bname VARCHAR(30) NOT NULL,
BPass VARCHAR(30) NOT NULL,
Address VARCHAR(200) NOT NULL,
Phone VARCHAR(30) NOT NULL,
PRIMARY KEY(Card_id),
UNIQUE(Ssn));

DROP TABLE IF EXISTS BOOK_LOANS;
CREATE TABLE BOOK_LOANS(
Loan_id INT AUTO_INCREMENT,
Book_id INT,
Card_id INT,
Date_out DATE,
Due_date DATE,
Date_in DATE,
PRIMARY KEY(Loan_id),
FOREIGN KEY(Book_id) REFERENCES BOOK(Book_id),
FOREIGN KEY(Card_id) REFERENCES BORROWER(Card_id));

DROP TABLE IF EXISTS FINES;
CREATE TABLE FINES(
Loan_id INT,
Fine_amt FLOAT DEFAULT 0,
Paid BOOLEAN DEFAULT False,
PRIMARY KEY(Loan_id),
FOREIGN KEY(Loan_id) REFERENCES BOOK_LOANS(Loan_id));