SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ToDoTable](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[text] [varchar](30) NOT NULL,
	[dateUpdate] [date] NOT NULL,
	[isDeleted] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ToDoTable] ADD  CONSTRAINT [dateDef]  DEFAULT (getdate()) FOR [dateUpdate]
GO
ALTER TABLE [dbo].[ToDoTable] ADD  DEFAULT ((0)) FOR [isDeleted]
GO
